### ISSUE TITLE
Chef-related error

### ISSUE THREAD

**Issue by jpmcneal** [bowst/howst#1]
Thanks for your work on this, Ben!

While bringing the machine up, I received the following errors:
- stdin: is not a tty
- Error executing action `install` on resource 'apt_package[php5]'
- Chef never successfully completed! Any errors should be visible in the output above. Please fix your recipes so that they properly complete.

I'm running Vagrant 1.7.2 on OSX with these plugins: vagrant-berkshelf (4.0.2), vagrant-omnibus (1.4.1), and vagrant-share (1.1.3, system).

**Comment by dtraft** [comment]
Can confirm - seeing the same errors.

**Comment by dtraft** [comment]
Actually, only the the stdin: is not a tty error - this appears to be a minor ubuntu bug.  see: https://github.com/mitchellh/vagrant/issues/1673

**Comment by jpmcneal** [comment]
Drew didn't have this issue, so we debugged it a bit. Apparently, I was running a newer version of Vbox. I down-graded to version 4.3.16 and also did a apt-get update, then it worked fine.

**Comment by jpmcneal** [comment]
Closing... see above comment.
